### ISSUE TITLE
Doesnt work with nextcloud 18 rc2

### ISSUE THREAD

**Issue by NiTRoeSE** [nextcloud/photos#127]
Hi, the photos app doesnt work for me on Nextcloud 18 RC2.
Page are blank and dont displays any photos. 
Last working version was Nextcloud 17.0.2.

Browser console error message:

<img width="1760" alt="Bildschirmfoto 2020-01-18 um 13 41 45" src="https://user-images.githubusercontent.com/24574743/72663943-6d800300-39f8-11ea-87e1-e92c093c08a8.png">

Hope it can be fixed, maybe there is a workaround ?
Thanks for your work!

**Comment by skjnldsv** [comment]
This is already fixed with the stable 18.

**Comment by kesselb** [comment]
Thanks :+1: If people are still seeing this what do you suggest? There are some reports at help.nextcloud.com :confused:
