### ISSUE TITLE
Scrolling far down makes pictures stop loading on the bottom part of the screen/view

### ISSUE THREAD

**Issue by simeneriks1** [nextcloud/photos#214]
**Describe the bug**
Scrolling down in the photos app in NC18 too far, stop loading pictures and scrolling is impossible.
![Screenshot 2020-02-28 at 11 11 20](https://user-images.githubusercontent.com/41788048/75540005-84643d00-5a1b-11ea-9454-cd312aeb0e2f.png)

**To Reproduce**
1. Have more than 500-600 pictures
2. Scroll all the way as far as you can
3. Watch it stop because the bottom threshold is moving upwards, and therefore not loading more pictures

**Expected behavior**
I want the full screen to be filled up with pictures

**Screenshots**
Here i have scrolled further down. The bottom threshold for showing the pictures is faaar up.
If I keep scrolling i can't see any pictures.
![image](https://user-images.githubusercontent.com/41788048/75540205-db6a1200-5a1b-11ea-843e-c7846ba63d64.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS, Windows, Linux
 - Browser Chrome 81

**Browser log**
No logs

**Additional context**
It only shows bad when scrolling, on top it is all normal.

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by simeneriks1** [comment]
I think you misunderstand the bug - There is no output in the console as there are no crashes/errors/code related issues in this case. 
What happens is that I scroll and scroll, and the threshold for showing pictures at the bottom is moving upwards, so when i scroll, less and less pictures are visible.
I can do an effort and try to recreate this on a new installation.

I tried several times but there are no console output to show in this report.

I can also record a video to show you the issue, if that helps :)

**Comment by skjnldsv** [comment]
The console log is supposed to show some debug informations.
This is not always about errors or crashes ;)

![Capture d’écran_2020-03-02_08-17-40](https://user-images.githubusercontent.com/14975046/75653649-4dca3480-5c5e-11ea-9cc6-80c40d457006.png)

**Comment by simeneriks1** [comment]
Alright, sorry about that!

Here is a screenshot

![image](https://user-images.githubusercontent.com/41788048/75694120-4c255e80-5ca8-11ea-8156-68b65914d7bf.png)

Errors I see is mostly connected to other apps or issues. I hope it is of help :)

**Comment by skjnldsv** [comment]
Ah right, on the small dropdown with `log level`, please also enable verbose :)
![image](https://user-images.githubusercontent.com/14975046/75697385-454d1a80-5cad-11ea-99f1-98fcf0ee3a71.png)

**Comment by dennorske** [comment]
![image](https://user-images.githubusercontent.com/3287543/75808141-e2c84d00-5d86-11ea-94a2-11a996b30406.png)

![image](https://user-images.githubusercontent.com/3287543/75807917-87965a80-5d86-11ea-9976-0ef17ea8d6a5.png)

There you go :) Stops at page 24, can't scroll further unless I change the aspect ratio of my browser (resizing so the grid changes) 

I scrolled up so you could see the errors that popped up. Also while scrolling, I get a lot of the forced reflow messages

**Comment by skjnldsv** [comment]
What happens if you scroll up on the page then down again?

**Comment by dennorske** [comment]
If I scroll up and back down, the grid will slowly be fully visible again
as I scroll up, and as I scroll down again, the grid slowly fades away.

Imagine it being a too small grid, and as you scroll, that little
difference moves upwards (not even)

ons. 4. mar. 2020, 09:03 skrev John Molakvoæ <notifications@github.com>:

**Comment by simeneriks1** [comment]
I manage to reproduce the problem on a fresh install, but i need like 3k pictures to make it very noticeable.

I suspect the grid calculations are off by a few pixels, and this just continues to add up as you scroll down.

**Comment by simeneriks1** [comment]
Hi, any news on this or do you need more info?

**Comment by skjnldsv** [comment]
Unfortunately I just need time :(

**Comment by Mikescops** [comment]
This was indeed an incremental shift caused by the virtual grid computation.

With the new grid this should be fixed. See #468

**Comment by simeneriks1** [comment]
I am still facing the same issue.

The update fixed that the grid does not move slightly upwards, but it still **stops** loading pictures after a certain amount of scroll.

I can recreate this on a brand new installation with enough pictures in it, I have around 800 and i get down to about 500 pictures before it doesn't let me scroll more. Was this tested before it was pushed in production?

**Comment by Mikescops** [comment]
Are you trying on the master branch?

**Comment by simeneriks1** [comment]
Ahhhh I am very sorry about that. I didn't realize that "To be released" was tagged on the PR - I blindly assumed it was pushed to production. 

I'll give it a new try when the app has been updated. Sorry again for my ignorance, have a nice day.
Simen

**Comment by Mikescops** [comment]
This will be for Nextcloud 21 indeed :smile:

**Comment by skjnldsv** [comment]
> I'll give it a new try when the app has been updated. Sorry again for my ignorance, have a nice day.

No worries! Thank you very much for your interest, we'll eager for you to try the upcoming version! @Mikescops did an insane job! :tada: :rocket:

**Comment by guystreeter** [comment]
Can you please verify the fix for this issue is supposed to be in version 21? I'm running the current docker image, 21.0.2, and the Photos view hangs if I scroll it at all. I've left it sitting with the busy indicator for half an hour and it never completes. I get the same results on Firefox and Chrome (both on Linux).
It appears to be something timing-related, because if I have the browser console open, it scrolls properly one time. Then it leaves some random thumbnails blank when I scroll around.

**Comment by dennorske** [comment]
Yep this issue in specific is fixed! :) 

I hope you solve your problem though, good luck
