### ISSUE TITLE
Photos v32.0.1 introduces issue navigating next/previous images in file viewer

### ISSUE THREAD

**Issue by valdearg** [nextcloud/photos#3264]
**Describe the bug**
When in the file viewer, clicking on next/previous buttons has no effect.

**To Reproduce**
1. Go to a folder in file viewer
2. Click on picture in folder with multiple images.
3. Click next or previous.

**Expected behavior**
Next/previous image should show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 144.0

**Browser log**
```

On opening the image:

File info for /Photos/Instagram (Raider)/asami_gate/1393672786.666498095246234917.jpg fetched 
Object { filename: "/Photos/Instagram (Raider)/asami_gate/1393672786.666498095246234917.jpg", basename: "1393672786.666498095246234917.jpg", lastmod: "Mon, 19 Jul 2021 23:04:53 GMT", size: 106714, type: "file", etag: "f08c7fee7e5e487acb0186fc3d77682e", mime: "image/jpeg", tags: "", getcontentlength: 106714, getcontenttype: "image/jpeg", … }
Viewer.vue:669:1

Could not open file /Photos/Instagram (Raider)/asami_gate/1393672786.666498095246234917.jpg TypeError: can't access property "filename", a is undefined
    currentIndex Viewer.vue:802
    openFileInfo Viewer.vue:802
    openFile Viewer.vue:670
    file Viewer.vue:460
    VueJS 11
    open Viewer.js:313
    $5 viewerAction.ts:82
    execDefaultAction FileEntryMixin.ts:327
    click FileEntry.vue:5
    VueJS 33
Viewer.vue:681:1

Then when clicking on the next button:

TypeError: can't access property "mime", e is undefined
    openFileFromList Viewer.vue:820
    next Viewer.vue:1087
    VueJS 4
    next NcModal.mjs:432
    VueJS 4
vue.runtime.esm.js:3065:17

```

**Comment by svenhardwarepunk** [comment]
Have the same problem with a complete new installation from scratch. No addons activated so far. In the Photos-App the buttons work, in file viewer it is not working, also the Autoplay Button.
Tested with Firefox and Google-Chrome

**Comment by svenhardwarepunk** [comment]
Found out, that it is only not working if I'm logged in. If I share a public link of the folder, there it is working fine.

**Comment by brunoandradeSP** [comment]
I am experiencing the same issue with media scrolling directly in the browser.

Initially, I cleared the browser cache (Brave), but it did not resolve the problem. Then I tested on another computer using a different browser (Edge), and the issue persists.

On the server, I cleared the cache, applied all available updates, and restarted the system. Despite this, the problem continues on this version.

Nextcloud information:

```
Nextcloud installed: true
Version: 32.0.1.2
Version string: 32.0.1
Edition: -
Maintenance mode: false
Database upgrade needed: false
Product name: Nextcloud
Extended support: false
```
Photos app version: `5.0.0-dev.1`

**Comment by BKapelari** [comment]
Same here with NC 32.0.1. 
**But I don't think, that this is a problem of the Photos app. I think this is a Problem in [Nextcloud Viewer](https://github.com/nextcloud/viewer).**

> Could not open file /path/to/file.jpeg TypeError: can't access property "filename", a is undefined
>     currentIndex Viewer.vue:802
>     openFileInfo Viewer.vue:802

**Comment by brunoandradeSP** [comment]
> Same here with NC 32.0.1. **But I don't think, that this is a problem of the Photos app. I think this is a Problem in [Nextcloud Viewer](https://github.com/nextcloud/viewer).**
> 
> > Could not open file /path/to/file.jpeg TypeError: can't access property "filename", a is undefined
> > currentIndex Viewer.vue:802
> > openFileInfo Viewer.vue:802

I encountered an issue in the Nextcloud Viewer where it fails to open some files. According to the browser console output, it seems that the Viewer is trying to access properties of a file that does not exist in the internal loaded file list, which results in a TypeError when reading filename or mime.

Console output:

```
TypeError: Cannot read properties of undefined vue.rintime.esm.js:3065
(reading 'mime')
at r. openFileFromList (Viewer.vue: 820:1)
at r.next (Viewer.vue:1087:1)

```

I plan to try regenerating thumbnails and updating the file index to see if the issue persists.

**Comment by arnowelzel** [comment]
> I plan to try regenerating thumbnails and updating the file index to see if the issue persists.

I did this already - no change. Nextcloud 32.0.1 as well here. My test environment with Nextcloud 32.0.0 works fine though.

And yes, it is not the Photos app but the viewer in the Files app - which is still available, even if the Photos app is disabled.

**Comment by jolang** [comment]
The issue nextcloud/viewer#2990 was already fixed with pull request nextcloud/viewer#3005 and backported to all supported stable releases: 

- nextcloud/viewer#3007
- nextcloud/viewer#3008
- nextcloud/viewer#3009

**Comment by SeDi343** [comment]
> The issue [nextcloud/viewer#2990](https://github.com/nextcloud/viewer/issues/2990) was already fixed with pull request [nextcloud/viewer#3005](https://github.com/nextcloud/viewer/pull/3005) and backported to all supported stable releases:
> 
> * [[stable30] fix: files root detection for public shares viewer#3007](https://github.com/nextcloud/viewer/pull/3007)
> * [[stable31] fix: files root detection for public shares viewer#3008](https://github.com/nextcloud/viewer/pull/3008)
> * [[stable32] fix: files root detection for public shares viewer#3009](https://github.com/nextcloud/viewer/pull/3009)

When will the update arrive on stable for 32.0.1? Since I did not get any update so far and it is still broken on my side on all 3 nextcloud ikstances.

**Comment by jolang** [comment]
> > The issue [nextcloud/viewer#2990](https://github.com/nextcloud/viewer/issues/2990) was already fixed with pull request [nextcloud/viewer#3005](https://github.com/nextcloud/viewer/pull/3005) and backported to all supported stable releases:
> > 
> > * [[stable30] fix: files root detection for public shares viewer#3007](https://github.com/nextcloud/viewer/pull/3007)
> > * [[stable31] fix: files root detection for public shares viewer#3008](https://github.com/nextcloud/viewer/pull/3008)
> > * [[stable32] fix: files root detection for public shares viewer#3009](https://github.com/nextcloud/viewer/pull/3009)
> 
> When will the update arrive on stable for 32.0.1? Since I did not get any update so far and it is still broken on my side on all 3 nextcloud ikstances.

This is not an official statement. I think we will have to wait until the next round of stable milestones is released, which currently scheduled for November 20.

**Comment by Spajderix** [comment]
Just pulled the latest docker image and can confirm it fixed the issue for me. Appreciate the fix and all the hard work done on this awesome project. Thank You!

**Comment by lsr-dev** [comment]
I just updated my instance (non-docker) to 32.0.2 and can confirm that the issue is fixed.
