### ISSUE TITLE
Photos app - Does not load photos when scrolling down

### ISSUE THREAD

**Issue by shelterx** [nextcloud/photos#748]
I have a support thread open on the forum but I might just as well post a bug report here, I've tried everything to fix it but I can't find the error.

Nextcloud version: 21.0.1
Operating system and version: freebsd 13.0-release
Apache or nginx version: nginx - 1.18.0_49
PHP version : 7.4.16

The issue:
When I go to Photos (app) only the top images are shown, if i scroll down, the page shows a spinning circle and doesn’t load any more images.

(If I use the “Files app” to view photos instead, they all load properly.)

Is this the first time you’ve seen this error?:
Started happen in Nextcloud 21
I was on nextcloud 18.x before and there the photos app worked fine, I even tried a fresh install of Nextcloud, same error there, Photos won’t load if i scroll down.

Steps to replicate it:
1. Go to photos.
2. Scroll down.

Nextcloud config:
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '',
    1 => '',
    2 => '',
  ),
  'datadirectory' => '/usr/local/www/web-cloud-data',
  'dbtype' => 'mysql',
  'version' => '21.0.1.1',
  'overwrite.cli.url' => '',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'default_phone_region' => 'SE',
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    3 => 'OC\\Preview\\HEIC',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\Movie',
  ),
  'preview_max_x' => '1920',
  'preview_max_y' => '1080',
  'jpeg_quality' => '70',
);
```

No errors in the server logs.

This is how it look likes:
![image](https://user-images.githubusercontent.com/8688458/115711515-e3011e80-a373-11eb-9a65-e97505fa6c82.png)
When it is in that state, I can’t click Your videos either, it won’t load that page without a page reload.

Chrome dev console:
![image](https://user-images.githubusercontent.com/8688458/115711581-fd3afc80-a373-11eb-988c-8c26e933d5c1.png)

**Comment by eibex** [comment]
This happens on Firefox too. You can still view the photos by clicking on the last one and then using the navigation buttons/arrow keys, but this won't load the photos in the general view.

**Comment by stratege1401** [comment]
Hello

I just switch to a new server running unRAID 6.9.2, and some docker.

I have redis, nextcloud, mariadb. 

everything runs fine except with photo, witch react exactly as @shelterx describe.
My loglevel was set to 0, but nothing pop-up except thousands of deprecated alert ...
Loglevel 1 or 2 or 3 are pretty useless ( no warn, no error, no fatal ).

Tested on several system or browser, same behavior...

?? anything else to help ??

**Comment by stratege1401** [comment]
Ok, i found out i dont have troubles with Iridium browser .... 

I am investigation a cache problem ... or something link to https hsts

**Comment by stratege1401** [comment]
Test on a W10PRO fully updated to latest edition

Bug is persistant on those browsers, all clean-up, cache empty ....
- Chrome, Edge, Firefox_dev, Opera, Vivaldi, Brave; icedragon, epique.

No bug with iridium. The only one showing a lot of pics ...

Same test same result on a w10 VM with  Chrome, Edge, Firefox_dev, Opera, Vivaldi, Brave; icedragon, epique.
Same test same bugs on a VM with latest ubuntu ( gorilla something ... )

Definitely a bug for me.

**Comment by stratege1401** [comment]
Ok, replicate bug on a brand new server.

This time it is a Debian 11-RC1 Bullseyes, with php7.4.15 , Apache/2.4.46 (Debian), 10.5.9-MariaDB-1.
Nextcloud 21.0.1 

Unfortunately, again, nothing in the logs ( apache, php, nextcloud even browser )

only 45 pics shown,
"waiting/searching" circle is active on page bottom.

I replicate the exact same bug on another completely different server based on unRAID 9.6.2 with Netcloud 21.0.1  
The pics files are the same, the behavior is the same, the numbers of pics visible is the same ( 45/4000 )

If using another batch of files ( clean environment ) i have the same behavior too.

```
APPS Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - announcementcenter: 5.0.0
 - apporder: 0.12.0
 - auto_groups: 1.3.1
 - breezedark: 21.0.7
 - bruteforcesettings: 2.1.0
 - camerarawpreviews: 0.7.11
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contactsinteraction: 1.2.0
 - data_request: 1.8.0
 - dav: 1.17.1
 - defaultgroup: 0.3.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_downloadactivity: 1.10.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_snapshots: 1.0.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - group_default_quota: 0.1.1
 - groupquota: 0.1.5
 - impersonate: 1.8.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - occweb: 0.0.7
 - password_policy: 1.11.0
 - photos: 1.3.0
 - previewgenerator: 3.1.1
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.10.0
 - recommendations: 1.0.0
 - registration: 1.2.1
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - terms_of_service: 1.7.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_email: 2.0.0
 - twofactor_nextcloud_notification: 3.1.2
 - twofactor_totp: 6.0.0
 - twofactor_u2f: 6.1.0
 - twofactor_webauthn: 0.2.9
 - unsplash: 1.2.2
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - dashboard
 - encryption
 - files_external
 - user_ldap


7.4.15
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache


{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "n2.rkn.ovh",
        "192.168.1.71"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "enable_previews": true,
    "preview_max_x": 4096,
    "preview_max_y": 4096,
    "preview_max_filesize_image": 50,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\HEIC",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\Krita"
    ],
    "default_language": "fr",
    "default_phone_region": "FR",
    "knowledgebaseenabled": true,
    "dbtype": "mysql",
    "version": "21.0.1.1",
    "overwrite.cli.url": "https:\/\/n2.rkn.ovh",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "cache_chunk_gc_ttl": 86400,
    "filelocking.ttl": 3600,
    "auth.bruteforce.protection.enabled": false,
    "loglevel": 1,
    "updater.release.channel": "stable",
    "maintenance": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "occweb",
        "defaultgroup",
        "issuetemplate"
    ],
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": []
}


```

**Comment by jwhips** [comment]
Sharing my experience with this issue and how it appears to be working now.

While my permissions did appear OK - 

I ran root@nc:/etc/php/7.4/apache2# sudo -u www-data php /var/www/html/occ files:scan --all


This didn't appears to fix anything.  Out of my 25 years of IT experience, I did the unexpected... tried to break it. Something I am good at.

I zoomed in and out with my Brave browser... - up 500%, and back down to 90%. Then clicked the 'reset' for the zoom. Then hit refresh in the browser.

It's working now.  I get all the thumbnails showing up as I scroll?! 
If I close the browser, the problem does come back. I was able to resolve it again.  It's not consistent to fix.

To speak a universal tagline all may understand, "I jiggled the handle."

**Comment by jwhips** [comment]
One last thing to consider, if the browser zoom is at 50%, the page loads **no** picture previews. Tested in Chromium Browsers Edge and Brave.

**Comment by shelterx** [comment]
Latest Nextcloud does not fix this. Probably because it’a the Photos app that’s buggy and not Nextcloud server.

**Comment by andyxheli** [comment]
yup im having the same issue with the photos click on the tab shows the first few then just shows the loading circle   and nothing loads running Nextcloud 20.0.10

**Comment by andyxheli** [comment]
@skjnldsv when you get some free time can you look into this please.

**Comment by stratege1401** [comment]
Issue fix for me.

Done nothing except:
- updating nextcloud to 21.0.2
- updating Chrome to 91.0.4472.77 (Build officiel) (64 bits).
-  updating W10Pro to 21H1 19043.1023 Windows Feature Experience Pack 120.2212.2020.0

**Comment by jwhips** [comment]
I had updated to 20.0.10 ; but my updater was showing as still needing the update?  So I went CLI and tried the update.  Said update was in progress. rebooted.  Was updated successfully.

Checked GUI system for version / update.  This showed system issues with a php config and data issues.

disabled php output_buffering




I had to run (in maintenance mode)
   sudo -u www-data php ./occ db:add-missing-indices 
 
and

   ./occ db:convert-fileache-bignt

My photos now seems to load without issue... ?

**Comment by shelterx** [comment]
It's not fixed here after upgrading to 21.0.2. It does load more photos but stops after a while...
Setting php output_buffering did not help.
Nor did the above occ commands.
Upgrading Chrome did not help either.

**Comment by skjnldsv** [comment]
I guess might be the same as https://github.com/nextcloud/photos/issues/777

**Comment by shelterx** [comment]
Doesn't fix it, I tried the changes in NC 21 (not sure if it's depends on NC 22, I hacked the appinfo/info.xml file BUT it seemed to "work")
More photos did load properly, but still stops after a while.
If I press and hold down PgDown instead of just scrolling even more photos load but far from all I think and If I scroll back up, the page is blank.

**Comment by andyxheli** [comment]
@skjnldsv #783 dose not fix the issue on my server Im running NC 21.0.2

**Comment by skjnldsv** [comment]
> @skjnldsv #783 dose not fix the issue on my server Im running NC 21.0.2

Did you test it?
This is not released yet.

**Comment by andyxheli** [comment]
> > @skjnldsv #783 dose not fix the issue on my server Im running NC 21.0.2
> 
> Did you test it?
> This is not released yet.

I did apply the fix but still the same issue. Unless I applied the fix wrong.

**Comment by skjnldsv** [comment]
Cleared all caches?

**Comment by andyxheli** [comment]
> Cleared all caches?

Yes, I did.

**Comment by shelterx** [comment]
I tried several ways to make the fix work on NC 21.0.2, it does not work no matter how I apply it. To me there's not much difference (if any) from the photos app included in 21.0.2, photos still does not load properly, and scrolling down/up breaks eventually.

**Comment by andyxheli** [comment]
Should we reopen this ticket since no fix yet ?

**Comment by andyxheli** [comment]
Thanks @skjnldsv let us know if you want us to make any other changes for testing.

**Comment by andyxheli** [comment]
@skjnldsv I moved from PHP 7.4 to PHP 8.0 and the photos is now working idk if that tells you anything

**Comment by shelterx** [comment]
I can confirm, using php 8 fixes the problem.

**Comment by szaimen** [comment]
Could you please try to change your zoom level to find out if this is the same issue https://github.com/nextcloud/photos/issues/642 ? Seems to be related at least.

**Comment by shelterx** [comment]
I have tried changing the zoom before i switched to php 8, it did not help.

**Comment by tothf** [comment]
I had the same issue running 20.0.9-fpm-alpine docker image. Upgrade to 20.0.10-fpm-alpine fixed it.
I have a test instance running on 21.0.2-fpm-alpine. The issue was there with 21.0.1-fpm-alpine and the upgrade didn't fix it.

**Comment by rdbell** [comment]
I experienced this issue after upgrading to 21.0.3

I believe Cloudflare was serving an old cached version of vue.runtime.esm.js

Purging my Cloudflare cache fixed the issue.

**Comment by andyxheli** [comment]
Yes, looks like it's fixed in 21.0.3

**Comment by szaimen** [comment]
Great! Thanks for the feedback!

**Comment by guystreeter** [comment]
I have pulled the latest docker apache image, which reports version 21.0.3, I have cleared the browser cache and logged back in the nextcloud. I still see this happening.

**Comment by shelterx** [comment]
Hmm, the issue came back to me in 21.0.3... seems to be related to generating thumbnails "on the fly" now in the photos app.
After I ran preview generator  (occ preview:generate-all -vvv) it's working again.

**Comment by skjnldsv** [comment]
This is a different issue. If your webserver is not powerful enough to generate lots of thumbnails on-the-fly, there is nothing we can do here :shrug:

**Comment by guystreeter** [comment]
The issue is not that the scroll takes a lot of time. It never finishes. I have pre-generated thumbnails and it still freezes. The difference OP observed with pre-generated thumbnails may indicate the problem is timing-related.

**Comment by skjnldsv** [comment]
@guystreeter I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by guystreeter** [comment]
I navigated to the Photos app, the started the console, then scrolled. Is that what you needed to see?
![Screenshot from 2021-07-05 18-01-36](https://user-images.githubusercontent.com/49929301/124523097-2ab41580-ddbb-11eb-84dc-f0fb247a8fd3.png)

**Comment by skjnldsv** [comment]
to the opposite, open network, go to bottom, screenshot

**Comment by andyxheli** [comment]
@skjnldsv 

Here's my out put 

![image](https://user-images.githubusercontent.com/59488153/124611874-7ad0bd80-de37-11eb-8b5c-d7ba335f3db4.png)

**Comment by guystreeter** [comment]
> do the opposite, open network, go to bottom, screenshot

I think I did what your're saying. I navigated to Photos, opened network, scrolled, then took the screenshot.

**Comment by andyxheli** [comment]
@skjnldsv Issue on NC 22 it gets to a point and stops makes alot of /dav requests and stops 

![image](https://user-images.githubusercontent.com/59488153/124642342-5be12400-de55-11eb-94c1-93d78bfb6983.png)

**Comment by tothf** [comment]
Well, it starts to load properly but...
1. Go to photos
2. Scroll down to the bottom, the load will start
3. Scroll to the top
4. Scroll down, load won't continue and the whole page is kinda messed up. Errors in the console
<img width="2503" alt="Screenshot 2021-07-07 at 11 19 26" src="https://user-images.githubusercontent.com/6927606/124695154-403d5280-df15-11eb-9053-f4eb389efa0e.png">

**Comment by guystreeter** [comment]
I'm now running the nextcloud 22 apache docker image, and this scrolling problem has gone away for me.
I have no idea what changed.

**Comment by andyxheli** [comment]
Still an issue in 21.0.3

**Comment by andyxheli** [comment]
Just upgraded to 21.0.4 and the issue still present. :(

**Comment by koarlmichael** [comment]
It worked with Nextcloud 22.0.0. After updating to 22.1.0, the error is back.

**Comment by shelterx** [comment]
Seems very random if it works or not, you can have it working fine in one version then when upgrading it stops working... then after a few page refreshes it works again.

**Comment by andyxheli** [comment]
![image](https://user-images.githubusercontent.com/59488153/129490331-7d2c23bc-936b-40d2-8d09-a637de5d5d38.png)

**Comment by jeepeegit** [comment]
May sound strange and I will test it more often but it seems that if I set the browser to a different zoom level, for example 90%, the scrolling does go well.
Macbook, high sierra firefox & chrome.

**Comment by eibex** [comment]
On my end it doesn't work on any zoom level. Latest Firefox and latest Chrome.

**Comment by BrodyStone21** [comment]
Not working for me either, anything I should try? No errors in logging. Running Nextcloud with Redis nd MariaDB with a reverse proxy. It had worked before without a reverse proxy or Redis.

**Comment by shelterx** [comment]
Works well for the moment with Nextcloud 22.2.3 but I had to use preview generator and run 
`occ preview:generate-all -vvv`
otherwise it overloaded the server and stuff crashed.

**Comment by shelterx** [comment]
@meomeo187 I think it's gone for a while, then the issue comes back.

**Comment by Yiannis128** [comment]
This also crashes Nextcloud and forces the service to restart, I think… So I can't really use the photos app.

**Comment by eibex** [comment]
This issue seems fixed since NC23/24. Not sure if your issue is related @Yiannis128

**Comment by XLixl4snSU** [comment]
It's not fixed for me @eibex 

Though photos will load for me after a while (5-15s for every ~ 30 Photos), it's not nearly as fast as it should be. If I navigate to the folder from the left menu it works perfectly.

I thought about reinstalling the app but this isn't allowed by default.

**Comment by eibex** [comment]
Not loading the photos =/= slow loading. The issue a year ago was actually about photos not loading at all.

Do you have preview generator?

**Comment by XLixl4snSU** [comment]
@eibex Yes, all images are pre-generated. 

As I said, browsing folders works perfectly, previews load in a fracture of a second when scrolling.

**Comment by eibex** [comment]
Then I would open a new issue with error logs from your browser/server and your system configuration

**Comment by Luncheon3462** [comment]
I'm on 28.0.1 and having the same problem.   I can see the thumbnails when using the files app, but not in the photos app.  Instead, I just see a blank square with the file name listed.

**Comment by eibex** [comment]
Open a new issue. It's very different from what this used to be.

**Comment by xclsky1** [comment]
I'm on 29.0.3 and having the same problem.!!!

**Comment by shelterx** [comment]
29.0.4 is fine here, be sure to set up php/redis exactly as they describe. You can also teeak your database settings somewhat.
