### ISSUE TITLE
js bug in vue.runtime.esm.js

### ISSUE THREAD

**Issue by EmmanuelTuloup** [nextcloud/photos#938]
**Describe the bug**
after hundreds of photos seen, the process hangs, and  no more photos appears

**To Reproduce**
scroll down a hundreds of photos

**Expected behavior**
see all the photos when you scroll down

**Screenshots**
![image](https://user-images.githubusercontent.com/19147153/147565495-69af4d82-056c-4eb4-82ee-609e297ca2b4.png)

**Desktop (please complete the following information):**
 - OS:win 10
 - Browser firefox
 - Version 95.0.1

**Smartphone (please complete the following information):**

**Browser log**
TypeError: t is undefined
    VueJS 13
        cr
        E
        E
        E
        E
        vo
        _update
        r
        get
        run
        mn
        oe
        Kt
vue.runtime.esm.js:1888:12
    VueJS 5
        Zt
        Wt
        Yt
        oe
        Kt

<details>
<summary>How to access your browser console (Click to expand)</summary>

**Additional context**

**Comment by EmmanuelTuloup** [comment]
with chrome:

vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'key')
    at cr (vue.runtime.esm.js:5817)
    at vue.runtime.esm.js:6219
    at E (vue.runtime.esm.js:6319)
    at vue.runtime.esm.js:6193
    at E (vue.runtime.esm.js:6319)
    at a.vo.nodeOps [as __patch__] (vue.runtime.esm.js:6482)
    at a.t._update (vue.runtime.esm.js:3948)
    at a.r (vue.runtime.esm.js:4066)
    at yn.get (vue.runtime.esm.js:4479)
    at yn.run (vue.runtime.esm.js:4554)
Zt @ vue.runtime.esm.js:1888
Échec du chargement de la carte source par les Outils de développement : Impossible de charger le contenu de /index.php/js/activity/activity-sidebar.js.map?v=fe49d7c520f13702fb7b : Erreur HTTP : code d'état 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Échec du chargement de la carte source par les Outils de développement : Impossible de charger le contenu de /core/js/dist/main.js.map : Chargement annulé en raison d'un délai dépassé

**Comment by skjnldsv** [comment]
Hey! What's your nextcloud version?

**Comment by Yong-Cheh** [comment]
Maybe the same issue.
It happens after I add 51 new photos with the same timestamp.
I found it will stop loading at desktop, but work fine on the mobile.
Additionally, when I resize the browser to make it show 4 photos per row at desktop, it will work correctly.

Browser: Edge, Firefox
OS: win7,win10
Nextcloud: 23.0.2

log in Edge
***
TypeError: Cannot read properties of undefined (reading 'key')
    at lr (photos-main.js:2:836418)
    at photos-main.js:2:850783
    at w (photos-main.js:2:850945)
    at photos-main.js:2:850470
    at w (photos-main.js:2:850945)
    at a.yo.nodeOps [as __patch__] (photos-main.js:2:852080)
    at a.e._update (photos-main.js:2:829181)
    at a.r (photos-main.js:2:859501)
    at bn.get (photos-main.js:2:821534)
    at bn.run (photos-main.js:2:822418)
***

**Comment by Yong-Cheh** [comment]
Hmm... after running the [preview generator](https://github.com/rullzer/previewgenerator) with **occ preview:generate-all -vvv**, I see different result in Edge and Firefox. It showed up 35(7 * 5) photos in Firefox while Edge showed up 47(8 * 6 - 1) photos. But both of them got broken layout.
I test on mobile last night and got another result that although it work correctly while scrolling down, it mess up after scroll back to top.

## Type Error in Firefox
```
TypeError: e is undefined
    lr https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    w https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    w https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    w https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    w https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    yo https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    _update https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    r https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    get https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    run https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    An https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    it https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    et https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
photos-main.js:2:806411
    Ye https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    Ke https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    We https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    it https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
    et https://800man.chickenkiller.com/apps/photos/js/photos-main.js?v=5fc3f3c6-0:2
```
## Type Error in Edge
[800man.chickenkiller.com-1645673165870_edge.log](https://github.com/nextcloud/photos/files/8129542/800man.chickenkiller.com-1645673165870_edge.log)
## Recording the test of Firefox
![2022-02-24_11-07-09](https://user-images.githubusercontent.com/57202874/155456216-ac85e455-208f-42c7-af24-5766bb9bb3fa.gif)

**Comment by skjnldsv** [comment]
Please everyone, fix your setups so your webserver can serve sourcemaps.
That will really helps locating the errors :)

**Comment by Yong-Cheh** [comment]
Hi John, I'm at office, I'll try it when home(server is setup for home use).
Would you please tell me how to do this? Modify the config.php or something else?
I googled something like [this](https://github.com/nextcloud/server/pull/16006/files#diff-1e20915590315789be1e7a67e4eb4c61ba5340a941d62b8fd039c13f40ea2094), seems like modify the htacess to work. Is it?

**Comment by skjnldsv** [comment]
Hi, it higly depends on your setups. it's not a nextcloud config, but your webserver (apache, nginx...) and/or whatever reverse proxy you might have running in front.
Serving sourcemap allow your browser to properly understand the original code location (instead of the compiled and compressed javascript files)

It should look like that  (instead of the `photos-main.js:2`)
![image](https://user-images.githubusercontent.com/14975046/155483527-412601b4-dc7f-43e2-b218-aa882db2394c.png)

**Comment by skjnldsv** [comment]
EDIT: it seems the documentation lost some of this. I fixed it.
See https://github.com/nextcloud/documentation/pull/8095

**Comment by mchugh19** [comment]
I'm seeing a similar error as well. Nextcloud 26 with photos 2.2.0. After scrolling part way through an entry under "people", I only see blurry image previews and eventually blank white photo entries and nothing else loads.  

```
TypeError: Cannot read properties of undefined (reading 'key')
    at Lr (vue.runtime.esm.js:6442:15)
    at vue.runtime.esm.js:6820:25
    at E (vue.runtime.esm.js:6909:21)
    at vue.runtime.esm.js:6783:17
    at E (vue.runtime.esm.js:6909:21)
    at $a.nodeOps [as __patch__] (vue.runtime.esm.js:7077:17)
    at e._update (vue.runtime.esm.js:3769:25)
    at o.r (vue.runtime.esm.js:3875:16)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.run (vue.runtime.esm.js:3522:30)
```

Starting from the bottom, these errors show
3522:30
```
 /**
     * Scheduler job interface.
     * Will be called by the scheduler.
     */
    Watcher.prototype.run = function () {
        if (this.active) {
            var value = this.get();
```

3446:30
```
 /**
     * Evaluate the getter, and re-collect dependencies.
     */
    Watcher.prototype.get = function () {
        pushTarget(this);
        var value;
        var vm = this.vm;
        try {
            value = this.getter.call(vm, vm);
```

3875:15
```
 else {
        updateComponent = function () {
            vm._update(vm._render(), hydrating);
```

**Comment by marmolak** [comment]
Hello. I'm still encountering this issue on Nextcloud 27.1.4.

**Comment by carlosgalveias** [comment]
Hi, still having this issue, using snap Nextcloud 27.1.8

**Comment by joshtrichards** [comment]
Are you still experiencing this today?

Are some of your HTTP transactions under the *Network* tab of the browser inspector showing red? Some of these may be filling preview generations (i.e. overrun server, etc.) which can be influenced by various factors.

**Comment by mokeev1995** [comment]
@joshtrichards I'm still experiencing this. [Here's some details.](https://github.com/nextcloud/photos/issues/2558#issuecomment-2925228287) I can easily reproduce this on my server. In my case, this is AIO instance (Nextcloud Hub 9 (30.0.10))
